### PR TITLE
revamp and add focus to banner_pdist()

### PR DESCRIPTION
**Pull request by piyawatl**
Add focus (aka "Focused Selection Points") as another optional dimension in banner_pdist(), and change its calculation method to remove the dimensions of focus and pity from DP table.

### CODE REVIEW

**Comment by astral4** [comment]
I think the probability calculation is slightly off. With the following input:
```rust
let banners = [Banner {
    target: 1,
    subrate: 0.5,
    bonus_pulls: 0,
}];

let pulls = 57;

println!("{}", calculate(&banners, pulls));
```
The output is `0.50687826` instead of `0.5110453`. (Obviously, there's floating-point error, but it shouldn't affect the result by this much.)

**Comment by piyawatl** [comment]
It should be fixed for the above case now, as well as other simple cases I've tried checking against other methods, although for cases with Focus enabled I don't have another method to compare with yet.

**Comment by astral4** [comment]
The focus selection pity doesn't seem to be properly accounted for. With the following input:
```rust
let banners = [Banner {
    target: 1,
    subrate: 0.5,
    bonus_pulls: 0,
    has_focus: true,
}];

let pulls = 151;

println!("{}", calculate(&banners, pulls));
```
The output is `0.91531646`, but it should be `1.0`. When the target character isn't obtained in 150 pulls, there are 150 selection points and the target character should be guaranteed to drop on the 151st pull.

I should probably add some unit tests to automate these kinds of sanity checks...

**Comment by piyawatl** [comment]
> The output is `0.91531646`, but it should be `1.0`. When the target character isn't obtained in 150 pulls, there are 150 selection points and the target character should be guaranteed to drop on the 151st pull.

My understanding of the Focused Selection system is that accumulating 150 points only guarantees that the next 6-star will be the rate-up character, but does not guarantee that the rate-up character will immediately appear in the next roll. In other words, it is equivalent to temporarily setting the `subrate` to `1.0` only for the next 6-star, which could be anywhere from the 151st (assuming the rate-up character has never appeared) to the 248th roll.

**Comment by astral4** [comment]
Okay, that makes sense. I think this looks good, then.

Future goal: allow accounting for the 300-pull spark system (on limited banners).

**Pull request merged**
